# App/toolkit environment for services and sway-launched apps.

_JAVA_AWT_WM_NONREPARENTING=1
SDL_VIDEODRIVER=wayland
QT_QPA_PLATFORM=wayland-egl
QT_QPA_PLATFORMTHEME=gtk3
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
NO_AT_BRIDGE=1
ELECTRON_OZONE_PLATFORM_HINT=wayland
XCURSOR_PATH=${XDG_DATA_HOME}/icons:/usr/share/icons
BEMOJI_PICKER_CMD=fuzzel -d
